import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { AuthProviders } from 'providers/auth.providers'

import './globals.css'

const inter = Roboto({ subsets: ['cyrillic', 'latin'], weight: '500' })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AuthProviders>{children}</AuthProviders>
			</body>
		</html>
	)
}
